// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beozptrxancjagxzdxce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlb3pwdHJ4YW5jamFneHpkeGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTgxOTEsImV4cCI6MjA2NTY3NDE5MX0.fVCUj7O5QL5MQb8RJMEJwieSzvzNfsiAr38dnEY8rwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);